language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
matrix:
  allow_failures:
    - rust: stable
    - rust: nightly
script:
  - echo "Checking code formatting" ; cargo fmt -- --check
  - echo "Build project"  ; cargo build
  - echo "Run unit tests" ; cargo test
  - echo "Checking code lints" ; cargo clippy -- -D clippy
