[package]
name = "rsget"
version = "2.0.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "Apache-2.0"
edition = "2018"
readme = "README.md"

[dependencies]
anyhow = "1.0.26"
indicatif = "0.13.0"
reqwest = "0.10.0"
structopt = "0.3.7"
tokio = { version = "0.2", features = ["macros", "fs"] }

