[package]
name = "rsget"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]

[dependencies]
reqwest = "0.9.1"
env_logger = "0.5.13"
failure = "0.1.2"
structopt = "0.2.10"
indicatif = "0.9.0"
