[package]
name = "rsget"
version = "1.0.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "Apache-2.0"
edition = "2018"
readme = "README.md"

[dependencies]
reqwest = "0.9.17"
failure = "0.1.5"
structopt = "0.2.15"
indicatif = "0.11.0"
exitfailure = "0.5.1"
